SELECT
	MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS "DATE_OF BIRTH"
FROM
	MEMBER_PROFILE
WHERE
	TLNO IS NOT NULL
	AND EXTRACT(MONTH FROM DATE_OF_BIRTH)='03'
	AND GENDER = 'W'
ORDER BY
	MEMBER_ID ASC;